<?php
/**
 * Cost
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sawvant\Model;

use \ArrayAccess;
use \Sawvant\ObjectSerializer;

/**
 * Cost Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Cost implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cost';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'setup_cost' => 'float',
        'cutting_cost' => 'float',
        'stacking_cost' => 'float',
        'rotation_cost' => 'float',
        'cycle_cost' => 'float',
        'total_cost' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'setup_cost' => 'double',
        'cutting_cost' => 'double',
        'stacking_cost' => 'double',
        'rotation_cost' => 'double',
        'cycle_cost' => 'double',
        'total_cost' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'setup_cost' => false,
        'cutting_cost' => false,
        'stacking_cost' => false,
        'rotation_cost' => false,
        'cycle_cost' => false,
        'total_cost' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'setup_cost' => 'setup_cost',
        'cutting_cost' => 'cutting_cost',
        'stacking_cost' => 'stacking_cost',
        'rotation_cost' => 'rotation_cost',
        'cycle_cost' => 'cycle_cost',
        'total_cost' => 'total_cost'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'setup_cost' => 'setSetupCost',
        'cutting_cost' => 'setCuttingCost',
        'stacking_cost' => 'setStackingCost',
        'rotation_cost' => 'setRotationCost',
        'cycle_cost' => 'setCycleCost',
        'total_cost' => 'setTotalCost'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'setup_cost' => 'getSetupCost',
        'cutting_cost' => 'getCuttingCost',
        'stacking_cost' => 'getStackingCost',
        'rotation_cost' => 'getRotationCost',
        'cycle_cost' => 'getCycleCost',
        'total_cost' => 'getTotalCost'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('setup_cost', $data ?? [], null);
        $this->setIfExists('cutting_cost', $data ?? [], null);
        $this->setIfExists('stacking_cost', $data ?? [], null);
        $this->setIfExists('rotation_cost', $data ?? [], null);
        $this->setIfExists('cycle_cost', $data ?? [], null);
        $this->setIfExists('total_cost', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['setup_cost'] === null) {
            $invalidProperties[] = "'setup_cost' can't be null";
        }
        if ($this->container['cutting_cost'] === null) {
            $invalidProperties[] = "'cutting_cost' can't be null";
        }
        if ($this->container['stacking_cost'] === null) {
            $invalidProperties[] = "'stacking_cost' can't be null";
        }
        if ($this->container['rotation_cost'] === null) {
            $invalidProperties[] = "'rotation_cost' can't be null";
        }
        if ($this->container['cycle_cost'] === null) {
            $invalidProperties[] = "'cycle_cost' can't be null";
        }
        if ($this->container['total_cost'] === null) {
            $invalidProperties[] = "'total_cost' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets setup_cost
     *
     * @return float
     */
    public function getSetupCost()
    {
        return $this->container['setup_cost'];
    }

    /**
     * Sets setup_cost
     *
     * @param float $setup_cost setup_cost
     *
     * @return self
     */
    public function setSetupCost($setup_cost)
    {
        if (is_null($setup_cost)) {
            throw new \InvalidArgumentException('non-nullable setup_cost cannot be null');
        }
        $this->container['setup_cost'] = $setup_cost;

        return $this;
    }

    /**
     * Gets cutting_cost
     *
     * @return float
     */
    public function getCuttingCost()
    {
        return $this->container['cutting_cost'];
    }

    /**
     * Sets cutting_cost
     *
     * @param float $cutting_cost cutting_cost
     *
     * @return self
     */
    public function setCuttingCost($cutting_cost)
    {
        if (is_null($cutting_cost)) {
            throw new \InvalidArgumentException('non-nullable cutting_cost cannot be null');
        }
        $this->container['cutting_cost'] = $cutting_cost;

        return $this;
    }

    /**
     * Gets stacking_cost
     *
     * @return float
     */
    public function getStackingCost()
    {
        return $this->container['stacking_cost'];
    }

    /**
     * Sets stacking_cost
     *
     * @param float $stacking_cost stacking_cost
     *
     * @return self
     */
    public function setStackingCost($stacking_cost)
    {
        if (is_null($stacking_cost)) {
            throw new \InvalidArgumentException('non-nullable stacking_cost cannot be null');
        }
        $this->container['stacking_cost'] = $stacking_cost;

        return $this;
    }

    /**
     * Gets rotation_cost
     *
     * @return float
     */
    public function getRotationCost()
    {
        return $this->container['rotation_cost'];
    }

    /**
     * Sets rotation_cost
     *
     * @param float $rotation_cost rotation_cost
     *
     * @return self
     */
    public function setRotationCost($rotation_cost)
    {
        if (is_null($rotation_cost)) {
            throw new \InvalidArgumentException('non-nullable rotation_cost cannot be null');
        }
        $this->container['rotation_cost'] = $rotation_cost;

        return $this;
    }

    /**
     * Gets cycle_cost
     *
     * @return float
     */
    public function getCycleCost()
    {
        return $this->container['cycle_cost'];
    }

    /**
     * Sets cycle_cost
     *
     * @param float $cycle_cost cycle_cost
     *
     * @return self
     */
    public function setCycleCost($cycle_cost)
    {
        if (is_null($cycle_cost)) {
            throw new \InvalidArgumentException('non-nullable cycle_cost cannot be null');
        }
        $this->container['cycle_cost'] = $cycle_cost;

        return $this;
    }

    /**
     * Gets total_cost
     *
     * @return float
     */
    public function getTotalCost()
    {
        return $this->container['total_cost'];
    }

    /**
     * Sets total_cost
     *
     * @param float $total_cost total_cost
     *
     * @return self
     */
    public function setTotalCost($total_cost)
    {
        if (is_null($total_cost)) {
            throw new \InvalidArgumentException('non-nullable total_cost cannot be null');
        }
        $this->container['total_cost'] = $total_cost;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


