<?php
/**
 * CostTariffs
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sawvant\Model;

use \ArrayAccess;
use \Sawvant\ObjectSerializer;

/**
 * CostTariffs Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CostTariffs implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CostTariffs';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'setup_cost' => 'float',
        'cost_per_meter' => 'float',
        'cost_per_rotation' => 'float',
        'cost_per_stack' => 'float',
        'cost_per_cycle' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'setup_cost' => 'double',
        'cost_per_meter' => 'double',
        'cost_per_rotation' => 'double',
        'cost_per_stack' => 'double',
        'cost_per_cycle' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'setup_cost' => false,
        'cost_per_meter' => false,
        'cost_per_rotation' => false,
        'cost_per_stack' => false,
        'cost_per_cycle' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'setup_cost' => 'setup_cost',
        'cost_per_meter' => 'cost_per_meter',
        'cost_per_rotation' => 'cost_per_rotation',
        'cost_per_stack' => 'cost_per_stack',
        'cost_per_cycle' => 'cost_per_cycle'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'setup_cost' => 'setSetupCost',
        'cost_per_meter' => 'setCostPerMeter',
        'cost_per_rotation' => 'setCostPerRotation',
        'cost_per_stack' => 'setCostPerStack',
        'cost_per_cycle' => 'setCostPerCycle'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'setup_cost' => 'getSetupCost',
        'cost_per_meter' => 'getCostPerMeter',
        'cost_per_rotation' => 'getCostPerRotation',
        'cost_per_stack' => 'getCostPerStack',
        'cost_per_cycle' => 'getCostPerCycle'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('setup_cost', $data ?? [], null);
        $this->setIfExists('cost_per_meter', $data ?? [], null);
        $this->setIfExists('cost_per_rotation', $data ?? [], null);
        $this->setIfExists('cost_per_stack', $data ?? [], null);
        $this->setIfExists('cost_per_cycle', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets setup_cost
     *
     * @return float|null
     */
    public function getSetupCost()
    {
        return $this->container['setup_cost'];
    }

    /**
     * Sets setup_cost
     *
     * @param float|null $setup_cost Fixed cost per job
     *
     * @return self
     */
    public function setSetupCost($setup_cost)
    {
        if (is_null($setup_cost)) {
            throw new \InvalidArgumentException('non-nullable setup_cost cannot be null');
        }
        $this->container['setup_cost'] = $setup_cost;

        return $this;
    }

    /**
     * Gets cost_per_meter
     *
     * @return float|null
     */
    public function getCostPerMeter()
    {
        return $this->container['cost_per_meter'];
    }

    /**
     * Sets cost_per_meter
     *
     * @param float|null $cost_per_meter Cost per meter of cut length
     *
     * @return self
     */
    public function setCostPerMeter($cost_per_meter)
    {
        if (is_null($cost_per_meter)) {
            throw new \InvalidArgumentException('non-nullable cost_per_meter cannot be null');
        }
        $this->container['cost_per_meter'] = $cost_per_meter;

        return $this;
    }

    /**
     * Gets cost_per_rotation
     *
     * @return float|null
     */
    public function getCostPerRotation()
    {
        return $this->container['cost_per_rotation'];
    }

    /**
     * Sets cost_per_rotation
     *
     * @param float|null $cost_per_rotation cost_per_rotation
     *
     * @return self
     */
    public function setCostPerRotation($cost_per_rotation)
    {
        if (is_null($cost_per_rotation)) {
            throw new \InvalidArgumentException('non-nullable cost_per_rotation cannot be null');
        }
        $this->container['cost_per_rotation'] = $cost_per_rotation;

        return $this;
    }

    /**
     * Gets cost_per_stack
     *
     * @return float|null
     */
    public function getCostPerStack()
    {
        return $this->container['cost_per_stack'];
    }

    /**
     * Sets cost_per_stack
     *
     * @param float|null $cost_per_stack cost_per_stack
     *
     * @return self
     */
    public function setCostPerStack($cost_per_stack)
    {
        if (is_null($cost_per_stack)) {
            throw new \InvalidArgumentException('non-nullable cost_per_stack cannot be null');
        }
        $this->container['cost_per_stack'] = $cost_per_stack;

        return $this;
    }

    /**
     * Gets cost_per_cycle
     *
     * @return float|null
     */
    public function getCostPerCycle()
    {
        return $this->container['cost_per_cycle'];
    }

    /**
     * Sets cost_per_cycle
     *
     * @param float|null $cost_per_cycle cost_per_cycle
     *
     * @return self
     */
    public function setCostPerCycle($cost_per_cycle)
    {
        if (is_null($cost_per_cycle)) {
            throw new \InvalidArgumentException('non-nullable cost_per_cycle cannot be null');
        }
        $this->container['cost_per_cycle'] = $cost_per_cycle;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


