<?php
/**
 * GrainDirection
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sawvant\Model;
use \Sawvant\ObjectSerializer;

/**
 * GrainDirection Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GrainDirection
{
    /**
     * Possible values of this enum
     */
    public const NONE = 'none';

    public const LENGTH = 'length';

    public const WIDTH = 'width';

    public const FREE_SAME = 'free_same';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::LENGTH,
            self::WIDTH,
            self::FREE_SAME
        ];
    }
}


