<?php
/**
 * Machine
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sawvant\Model;

use \ArrayAccess;
use \Sawvant\ObjectSerializer;

/**
 * Machine Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Machine implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Machine';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'blade_thickness' => 'float',
        'max_levels' => 'int',
        'max_stack_height' => 'float',
        'cut_direction' => '\Sawvant\Model\CutDirection'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'blade_thickness' => 'double',
        'max_levels' => null,
        'max_stack_height' => 'double',
        'cut_direction' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'blade_thickness' => false,
        'max_levels' => false,
        'max_stack_height' => false,
        'cut_direction' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'blade_thickness' => 'blade_thickness',
        'max_levels' => 'max_levels',
        'max_stack_height' => 'max_stack_height',
        'cut_direction' => 'cut_direction'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'blade_thickness' => 'setBladeThickness',
        'max_levels' => 'setMaxLevels',
        'max_stack_height' => 'setMaxStackHeight',
        'cut_direction' => 'setCutDirection'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'blade_thickness' => 'getBladeThickness',
        'max_levels' => 'getMaxLevels',
        'max_stack_height' => 'getMaxStackHeight',
        'cut_direction' => 'getCutDirection'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('blade_thickness', $data ?? [], null);
        $this->setIfExists('max_levels', $data ?? [], null);
        $this->setIfExists('max_stack_height', $data ?? [], null);
        $this->setIfExists('cut_direction', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['blade_thickness'] === null) {
            $invalidProperties[] = "'blade_thickness' can't be null";
        }
        if ($this->container['max_levels'] === null) {
            $invalidProperties[] = "'max_levels' can't be null";
        }
        if (($this->container['max_levels'] > 3)) {
            $invalidProperties[] = "invalid value for 'max_levels', must be smaller than or equal to 3.";
        }

        if (($this->container['max_levels'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_levels', must be bigger than or equal to 1.";
        }

        if ($this->container['cut_direction'] === null) {
            $invalidProperties[] = "'cut_direction' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blade_thickness
     *
     * @return float
     */
    public function getBladeThickness()
    {
        return $this->container['blade_thickness'];
    }

    /**
     * Sets blade_thickness
     *
     * @param float $blade_thickness Kerf width in mm
     *
     * @return self
     */
    public function setBladeThickness($blade_thickness)
    {
        if (is_null($blade_thickness)) {
            throw new \InvalidArgumentException('non-nullable blade_thickness cannot be null');
        }
        $this->container['blade_thickness'] = $blade_thickness;

        return $this;
    }

    /**
     * Gets max_levels
     *
     * @return int
     */
    public function getMaxLevels()
    {
        return $this->container['max_levels'];
    }

    /**
     * Sets max_levels
     *
     * @param int $max_levels Cut pattern complexity (1-3)
     *
     * @return self
     */
    public function setMaxLevels($max_levels)
    {
        if (is_null($max_levels)) {
            throw new \InvalidArgumentException('non-nullable max_levels cannot be null');
        }

        if (($max_levels > 3)) {
            throw new \InvalidArgumentException('invalid value for $max_levels when calling Machine., must be smaller than or equal to 3.');
        }
        if (($max_levels < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_levels when calling Machine., must be bigger than or equal to 1.');
        }

        $this->container['max_levels'] = $max_levels;

        return $this;
    }

    /**
     * Gets max_stack_height
     *
     * @return float|null
     */
    public function getMaxStackHeight()
    {
        return $this->container['max_stack_height'];
    }

    /**
     * Sets max_stack_height
     *
     * @param float|null $max_stack_height Maximum stack height in mm for batch cutting
     *
     * @return self
     */
    public function setMaxStackHeight($max_stack_height)
    {
        if (is_null($max_stack_height)) {
            throw new \InvalidArgumentException('non-nullable max_stack_height cannot be null');
        }
        $this->container['max_stack_height'] = $max_stack_height;

        return $this;
    }

    /**
     * Gets cut_direction
     *
     * @return \Sawvant\Model\CutDirection
     */
    public function getCutDirection()
    {
        return $this->container['cut_direction'];
    }

    /**
     * Sets cut_direction
     *
     * @param \Sawvant\Model\CutDirection $cut_direction cut_direction
     *
     * @return self
     */
    public function setCutDirection($cut_direction)
    {
        if (is_null($cut_direction)) {
            throw new \InvalidArgumentException('non-nullable cut_direction cannot be null');
        }
        $this->container['cut_direction'] = $cut_direction;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


