<?php
/**
 * Metrics
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sawvant\Model;

use \ArrayAccess;
use \Sawvant\ObjectSerializer;

/**
 * Metrics Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Metrics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Metrics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total_cut_length' => 'float',
        'total_cuts' => 'int',
        'total_rotations' => 'int',
        'total_stacks' => 'int',
        'cut_cycles' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total_cut_length' => 'double',
        'total_cuts' => null,
        'total_rotations' => null,
        'total_stacks' => null,
        'cut_cycles' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total_cut_length' => false,
        'total_cuts' => false,
        'total_rotations' => false,
        'total_stacks' => false,
        'cut_cycles' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_cut_length' => 'total_cut_length',
        'total_cuts' => 'total_cuts',
        'total_rotations' => 'total_rotations',
        'total_stacks' => 'total_stacks',
        'cut_cycles' => 'cut_cycles'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_cut_length' => 'setTotalCutLength',
        'total_cuts' => 'setTotalCuts',
        'total_rotations' => 'setTotalRotations',
        'total_stacks' => 'setTotalStacks',
        'cut_cycles' => 'setCutCycles'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_cut_length' => 'getTotalCutLength',
        'total_cuts' => 'getTotalCuts',
        'total_rotations' => 'getTotalRotations',
        'total_stacks' => 'getTotalStacks',
        'cut_cycles' => 'getCutCycles'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('total_cut_length', $data ?? [], null);
        $this->setIfExists('total_cuts', $data ?? [], null);
        $this->setIfExists('total_rotations', $data ?? [], null);
        $this->setIfExists('total_stacks', $data ?? [], null);
        $this->setIfExists('cut_cycles', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['total_cut_length'] === null) {
            $invalidProperties[] = "'total_cut_length' can't be null";
        }
        if ($this->container['total_cuts'] === null) {
            $invalidProperties[] = "'total_cuts' can't be null";
        }
        if ($this->container['total_rotations'] === null) {
            $invalidProperties[] = "'total_rotations' can't be null";
        }
        if ($this->container['total_stacks'] === null) {
            $invalidProperties[] = "'total_stacks' can't be null";
        }
        if ($this->container['cut_cycles'] === null) {
            $invalidProperties[] = "'cut_cycles' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_cut_length
     *
     * @return float
     */
    public function getTotalCutLength()
    {
        return $this->container['total_cut_length'];
    }

    /**
     * Sets total_cut_length
     *
     * @param float $total_cut_length Total cut length in mm
     *
     * @return self
     */
    public function setTotalCutLength($total_cut_length)
    {
        if (is_null($total_cut_length)) {
            throw new \InvalidArgumentException('non-nullable total_cut_length cannot be null');
        }
        $this->container['total_cut_length'] = $total_cut_length;

        return $this;
    }

    /**
     * Gets total_cuts
     *
     * @return int
     */
    public function getTotalCuts()
    {
        return $this->container['total_cuts'];
    }

    /**
     * Sets total_cuts
     *
     * @param int $total_cuts total_cuts
     *
     * @return self
     */
    public function setTotalCuts($total_cuts)
    {
        if (is_null($total_cuts)) {
            throw new \InvalidArgumentException('non-nullable total_cuts cannot be null');
        }
        $this->container['total_cuts'] = $total_cuts;

        return $this;
    }

    /**
     * Gets total_rotations
     *
     * @return int
     */
    public function getTotalRotations()
    {
        return $this->container['total_rotations'];
    }

    /**
     * Sets total_rotations
     *
     * @param int $total_rotations total_rotations
     *
     * @return self
     */
    public function setTotalRotations($total_rotations)
    {
        if (is_null($total_rotations)) {
            throw new \InvalidArgumentException('non-nullable total_rotations cannot be null');
        }
        $this->container['total_rotations'] = $total_rotations;

        return $this;
    }

    /**
     * Gets total_stacks
     *
     * @return int
     */
    public function getTotalStacks()
    {
        return $this->container['total_stacks'];
    }

    /**
     * Sets total_stacks
     *
     * @param int $total_stacks total_stacks
     *
     * @return self
     */
    public function setTotalStacks($total_stacks)
    {
        if (is_null($total_stacks)) {
            throw new \InvalidArgumentException('non-nullable total_stacks cannot be null');
        }
        $this->container['total_stacks'] = $total_stacks;

        return $this;
    }

    /**
     * Gets cut_cycles
     *
     * @return int
     */
    public function getCutCycles()
    {
        return $this->container['cut_cycles'];
    }

    /**
     * Sets cut_cycles
     *
     * @param int $cut_cycles cut_cycles
     *
     * @return self
     */
    public function setCutCycles($cut_cycles)
    {
        if (is_null($cut_cycles)) {
            throw new \InvalidArgumentException('non-nullable cut_cycles cannot be null');
        }
        $this->container['cut_cycles'] = $cut_cycles;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


