<?php
/**
 * OptimizeRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sawvant\Model;

use \ArrayAccess;
use \Sawvant\ObjectSerializer;

/**
 * OptimizeRequest Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OptimizeRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OptimizeRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'parts' => '\Sawvant\Model\Part[]',
        'sheets' => '\Sawvant\Model\Sheet[]',
        'machine' => '\Sawvant\Model\Machine',
        'strategy' => 'string',
        'cost_tariffs' => '\Sawvant\Model\CostTariffs'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'parts' => null,
        'sheets' => null,
        'machine' => null,
        'strategy' => null,
        'cost_tariffs' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'parts' => false,
        'sheets' => false,
        'machine' => false,
        'strategy' => false,
        'cost_tariffs' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parts' => 'parts',
        'sheets' => 'sheets',
        'machine' => 'machine',
        'strategy' => 'strategy',
        'cost_tariffs' => 'cost_tariffs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parts' => 'setParts',
        'sheets' => 'setSheets',
        'machine' => 'setMachine',
        'strategy' => 'setStrategy',
        'cost_tariffs' => 'setCostTariffs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parts' => 'getParts',
        'sheets' => 'getSheets',
        'machine' => 'getMachine',
        'strategy' => 'getStrategy',
        'cost_tariffs' => 'getCostTariffs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STRATEGY_FAST = 'fast';
    public const STRATEGY_THOROUGH = 'thorough';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStrategyAllowableValues()
    {
        return [
            self::STRATEGY_FAST,
            self::STRATEGY_THOROUGH,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('parts', $data ?? [], null);
        $this->setIfExists('sheets', $data ?? [], null);
        $this->setIfExists('machine', $data ?? [], null);
        $this->setIfExists('strategy', $data ?? [], 'fast');
        $this->setIfExists('cost_tariffs', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['parts'] === null) {
            $invalidProperties[] = "'parts' can't be null";
        }
        if ((count($this->container['parts']) > 5000)) {
            $invalidProperties[] = "invalid value for 'parts', number of items must be less than or equal to 5000.";
        }

        if ((count($this->container['parts']) < 1)) {
            $invalidProperties[] = "invalid value for 'parts', number of items must be greater than or equal to 1.";
        }

        if ($this->container['sheets'] === null) {
            $invalidProperties[] = "'sheets' can't be null";
        }
        if ((count($this->container['sheets']) > 100)) {
            $invalidProperties[] = "invalid value for 'sheets', number of items must be less than or equal to 100.";
        }

        if ((count($this->container['sheets']) < 1)) {
            $invalidProperties[] = "invalid value for 'sheets', number of items must be greater than or equal to 1.";
        }

        if ($this->container['machine'] === null) {
            $invalidProperties[] = "'machine' can't be null";
        }
        $allowedValues = $this->getStrategyAllowableValues();
        if (!is_null($this->container['strategy']) && !in_array($this->container['strategy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'strategy', must be one of '%s'",
                $this->container['strategy'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parts
     *
     * @return \Sawvant\Model\Part[]
     */
    public function getParts()
    {
        return $this->container['parts'];
    }

    /**
     * Sets parts
     *
     * @param \Sawvant\Model\Part[] $parts parts
     *
     * @return self
     */
    public function setParts($parts)
    {
        if (is_null($parts)) {
            throw new \InvalidArgumentException('non-nullable parts cannot be null');
        }

        if ((count($parts) > 5000)) {
            throw new \InvalidArgumentException('invalid value for $parts when calling OptimizeRequest., number of items must be less than or equal to 5000.');
        }
        if ((count($parts) < 1)) {
            throw new \InvalidArgumentException('invalid length for $parts when calling OptimizeRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['parts'] = $parts;

        return $this;
    }

    /**
     * Gets sheets
     *
     * @return \Sawvant\Model\Sheet[]
     */
    public function getSheets()
    {
        return $this->container['sheets'];
    }

    /**
     * Sets sheets
     *
     * @param \Sawvant\Model\Sheet[] $sheets sheets
     *
     * @return self
     */
    public function setSheets($sheets)
    {
        if (is_null($sheets)) {
            throw new \InvalidArgumentException('non-nullable sheets cannot be null');
        }

        if ((count($sheets) > 100)) {
            throw new \InvalidArgumentException('invalid value for $sheets when calling OptimizeRequest., number of items must be less than or equal to 100.');
        }
        if ((count($sheets) < 1)) {
            throw new \InvalidArgumentException('invalid length for $sheets when calling OptimizeRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['sheets'] = $sheets;

        return $this;
    }

    /**
     * Gets machine
     *
     * @return \Sawvant\Model\Machine
     */
    public function getMachine()
    {
        return $this->container['machine'];
    }

    /**
     * Sets machine
     *
     * @param \Sawvant\Model\Machine $machine machine
     *
     * @return self
     */
    public function setMachine($machine)
    {
        if (is_null($machine)) {
            throw new \InvalidArgumentException('non-nullable machine cannot be null');
        }
        $this->container['machine'] = $machine;

        return $this;
    }

    /**
     * Gets strategy
     *
     * @return string|null
     */
    public function getStrategy()
    {
        return $this->container['strategy'];
    }

    /**
     * Sets strategy
     *
     * @param string|null $strategy Solve strategy. \"fast\" runs all greedy solvers concurrently. \"thorough\" adds Gilmore-Gomory column generation for optimal patterns. Each strategy has its own rate limit quota.
     *
     * @return self
     */
    public function setStrategy($strategy)
    {
        if (is_null($strategy)) {
            throw new \InvalidArgumentException('non-nullable strategy cannot be null');
        }
        $allowedValues = $this->getStrategyAllowableValues();
        if (!in_array($strategy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'strategy', must be one of '%s'",
                    $strategy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['strategy'] = $strategy;

        return $this;
    }

    /**
     * Gets cost_tariffs
     *
     * @return \Sawvant\Model\CostTariffs|null
     */
    public function getCostTariffs()
    {
        return $this->container['cost_tariffs'];
    }

    /**
     * Sets cost_tariffs
     *
     * @param \Sawvant\Model\CostTariffs|null $cost_tariffs cost_tariffs
     *
     * @return self
     */
    public function setCostTariffs($cost_tariffs)
    {
        if (is_null($cost_tariffs)) {
            throw new \InvalidArgumentException('non-nullable cost_tariffs cannot be null');
        }
        $this->container['cost_tariffs'] = $cost_tariffs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


