<?php
/**
 * Summary
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sawvant\Model;

use \ArrayAccess;
use \Sawvant\ObjectSerializer;

/**
 * Summary Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Summary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Summary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total_sheets' => 'int',
        'yield_percent' => 'float',
        'waste_percent' => 'float',
        'waste_area' => 'float',
        'unplaced_parts' => 'string[]',
        'sheets_used' => '\Sawvant\Model\SheetUsage[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total_sheets' => null,
        'yield_percent' => 'double',
        'waste_percent' => 'double',
        'waste_area' => 'double',
        'unplaced_parts' => null,
        'sheets_used' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total_sheets' => false,
        'yield_percent' => false,
        'waste_percent' => false,
        'waste_area' => false,
        'unplaced_parts' => false,
        'sheets_used' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_sheets' => 'total_sheets',
        'yield_percent' => 'yield_percent',
        'waste_percent' => 'waste_percent',
        'waste_area' => 'waste_area',
        'unplaced_parts' => 'unplaced_parts',
        'sheets_used' => 'sheets_used'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_sheets' => 'setTotalSheets',
        'yield_percent' => 'setYieldPercent',
        'waste_percent' => 'setWastePercent',
        'waste_area' => 'setWasteArea',
        'unplaced_parts' => 'setUnplacedParts',
        'sheets_used' => 'setSheetsUsed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_sheets' => 'getTotalSheets',
        'yield_percent' => 'getYieldPercent',
        'waste_percent' => 'getWastePercent',
        'waste_area' => 'getWasteArea',
        'unplaced_parts' => 'getUnplacedParts',
        'sheets_used' => 'getSheetsUsed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('total_sheets', $data ?? [], null);
        $this->setIfExists('yield_percent', $data ?? [], null);
        $this->setIfExists('waste_percent', $data ?? [], null);
        $this->setIfExists('waste_area', $data ?? [], null);
        $this->setIfExists('unplaced_parts', $data ?? [], null);
        $this->setIfExists('sheets_used', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['total_sheets'] === null) {
            $invalidProperties[] = "'total_sheets' can't be null";
        }
        if ($this->container['yield_percent'] === null) {
            $invalidProperties[] = "'yield_percent' can't be null";
        }
        if (($this->container['yield_percent'] > 100)) {
            $invalidProperties[] = "invalid value for 'yield_percent', must be smaller than or equal to 100.";
        }

        if (($this->container['yield_percent'] < 0)) {
            $invalidProperties[] = "invalid value for 'yield_percent', must be bigger than or equal to 0.";
        }

        if ($this->container['waste_percent'] === null) {
            $invalidProperties[] = "'waste_percent' can't be null";
        }
        if ($this->container['waste_area'] === null) {
            $invalidProperties[] = "'waste_area' can't be null";
        }
        if ($this->container['sheets_used'] === null) {
            $invalidProperties[] = "'sheets_used' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_sheets
     *
     * @return int
     */
    public function getTotalSheets()
    {
        return $this->container['total_sheets'];
    }

    /**
     * Sets total_sheets
     *
     * @param int $total_sheets total_sheets
     *
     * @return self
     */
    public function setTotalSheets($total_sheets)
    {
        if (is_null($total_sheets)) {
            throw new \InvalidArgumentException('non-nullable total_sheets cannot be null');
        }
        $this->container['total_sheets'] = $total_sheets;

        return $this;
    }

    /**
     * Gets yield_percent
     *
     * @return float
     */
    public function getYieldPercent()
    {
        return $this->container['yield_percent'];
    }

    /**
     * Sets yield_percent
     *
     * @param float $yield_percent yield_percent
     *
     * @return self
     */
    public function setYieldPercent($yield_percent)
    {
        if (is_null($yield_percent)) {
            throw new \InvalidArgumentException('non-nullable yield_percent cannot be null');
        }

        if (($yield_percent > 100)) {
            throw new \InvalidArgumentException('invalid value for $yield_percent when calling Summary., must be smaller than or equal to 100.');
        }
        if (($yield_percent < 0)) {
            throw new \InvalidArgumentException('invalid value for $yield_percent when calling Summary., must be bigger than or equal to 0.');
        }

        $this->container['yield_percent'] = $yield_percent;

        return $this;
    }

    /**
     * Gets waste_percent
     *
     * @return float
     */
    public function getWastePercent()
    {
        return $this->container['waste_percent'];
    }

    /**
     * Sets waste_percent
     *
     * @param float $waste_percent waste_percent
     *
     * @return self
     */
    public function setWastePercent($waste_percent)
    {
        if (is_null($waste_percent)) {
            throw new \InvalidArgumentException('non-nullable waste_percent cannot be null');
        }
        $this->container['waste_percent'] = $waste_percent;

        return $this;
    }

    /**
     * Gets waste_area
     *
     * @return float
     */
    public function getWasteArea()
    {
        return $this->container['waste_area'];
    }

    /**
     * Sets waste_area
     *
     * @param float $waste_area mm²
     *
     * @return self
     */
    public function setWasteArea($waste_area)
    {
        if (is_null($waste_area)) {
            throw new \InvalidArgumentException('non-nullable waste_area cannot be null');
        }
        $this->container['waste_area'] = $waste_area;

        return $this;
    }

    /**
     * Gets unplaced_parts
     *
     * @return string[]|null
     */
    public function getUnplacedParts()
    {
        return $this->container['unplaced_parts'];
    }

    /**
     * Sets unplaced_parts
     *
     * @param string[]|null $unplaced_parts unplaced_parts
     *
     * @return self
     */
    public function setUnplacedParts($unplaced_parts)
    {
        if (is_null($unplaced_parts)) {
            throw new \InvalidArgumentException('non-nullable unplaced_parts cannot be null');
        }
        $this->container['unplaced_parts'] = $unplaced_parts;

        return $this;
    }

    /**
     * Gets sheets_used
     *
     * @return \Sawvant\Model\SheetUsage[]
     */
    public function getSheetsUsed()
    {
        return $this->container['sheets_used'];
    }

    /**
     * Sets sheets_used
     *
     * @param \Sawvant\Model\SheetUsage[] $sheets_used sheets_used
     *
     * @return self
     */
    public function setSheetsUsed($sheets_used)
    {
        if (is_null($sheets_used)) {
            throw new \InvalidArgumentException('non-nullable sheets_used cannot be null');
        }
        $this->container['sheets_used'] = $sheets_used;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


