<?php
/**
 * CostTariffsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sawvant\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CostTariffsTest Class Doc Comment
 *
 * @category    Class
 * @description CostTariffs
 * @package     Sawvant
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CostTariffsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CostTariffs"
     */
    public function testCostTariffs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "setup_cost"
     */
    public function testPropertySetupCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_per_meter"
     */
    public function testPropertyCostPerMeter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_per_rotation"
     */
    public function testPropertyCostPerRotation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_per_stack"
     */
    public function testPropertyCostPerStack()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_per_cycle"
     */
    public function testPropertyCostPerCycle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
