<?php
/**
 * EdgeCorrectionTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sawvant\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EdgeCorrectionTest Class Doc Comment
 *
 * @category    Class
 * @description EdgeCorrection
 * @package     Sawvant
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EdgeCorrectionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EdgeCorrection"
     */
    public function testEdgeCorrection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "top"
     */
    public function testPropertyTop()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bottom"
     */
    public function testPropertyBottom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "left"
     */
    public function testPropertyLeft()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "right"
     */
    public function testPropertyRight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
