<?php
/**
 * OptimizeRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sawvant\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OptimizeRequestTest Class Doc Comment
 *
 * @category    Class
 * @description OptimizeRequest
 * @package     Sawvant
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OptimizeRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OptimizeRequest"
     */
    public function testOptimizeRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "parts"
     */
    public function testPropertyParts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sheets"
     */
    public function testPropertySheets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "machine"
     */
    public function testPropertyMachine()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "strategy"
     */
    public function testPropertyStrategy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_tariffs"
     */
    public function testPropertyCostTariffs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
