<?php
/**
 * PlacementTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sawvant\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PlacementTest Class Doc Comment
 *
 * @category    Class
 * @description Placement
 * @package     Sawvant
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PlacementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Placement"
     */
    public function testPlacement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "part_id"
     */
    public function testPropertyPartId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sheet_id"
     */
    public function testPropertySheetId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rotated"
     */
    public function testPropertyRotated()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "grain"
     */
    public function testPropertyGrain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
