<?php
/**
 * JobsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sawvant Cutting Optimization API — PHP SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Sawvant\Test\Api;

use \Sawvant\Configuration;
use \Sawvant\ApiException;
use \Sawvant\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * JobsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sawvant
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JobsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getJob
     *
     * Get job status.
     *
     */
    public function testGetJob()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for streamJob
     *
     * Stream job progress via SSE.
     *
     */
    public function testStreamJob()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
